clone:
  depth: full
pipelines:
 branches:
    development:
      - step:
          name: Deploy to GITHUB
          deployment: GITHUB
          script:
            - echo "Deploying to GITHUB"
            - apt-get install -y unzip git git-core libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
            - git push git@github.com:rgruiz/slothfashion-react.git
          
